"""recurring bill

Revision ID: 4195d1985b6b
Revises: 927ed575acbd
Create Date: 2022-12-07 15:44:58.143290

"""

# revision identifiers, used by Alembic.
revision = '4195d1985b6b'
down_revision = '927ed575acbd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bill', sa.Column('recurrence', sa.Integer(), nullable=True))
    op.add_column('bill_version', sa.Column('recurrence', sa.Integer(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bill_version', 'recurrence')
    op.drop_column('bill', 'recurrence')
    # ### end Alembic commands ###
